SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS X1 (
  X2 INT AUTO_INCREMENT PRIMARY KEY,
  X3 VARCHAR(12) NOT NULL,
  X4 VARCHAR(100) NOT NULL UNIQUE,
  X5 TEXT NOT NULL,
  X6 VARCHAR(45) NOT NULL,
  X7 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  X8 TINYINT(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS X9 (
  X10 INT AUTO_INCREMENT PRIMARY KEY,
  X11 VARCHAR(200) NOT NULL,
  X12 TEXT,
  X13 VARCHAR(255),
  X14 VARCHAR(255) NOT NULL,
  X15 DECIMAL(8,2) DEFAULT 0.00,
  X16 INT DEFAULT 0,
  X17 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS X18 (
  X19 INT AUTO_INCREMENT PRIMARY KEY,
  X20 INT NOT NULL,
  X21 DECIMAL(8,2) DEFAULT 0.00,
  X22 ENUM('pending','completed') DEFAULT 'completed',
  X23 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (X20) REFERENCES X1(X2) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS X24 (
  X25 INT AUTO_INCREMENT PRIMARY KEY,
  X26 INT NOT NULL,
  X27 INT NOT NULL,
  X28 DECIMAL(8,2),
  FOREIGN KEY (X26) REFERENCES X18(X19) ON DELETE CASCADE,
  FOREIGN KEY (X27) REFERENCES X9(X10) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS X29 (
  X30 INT AUTO_INCREMENT PRIMARY KEY,
  X31 INT NOT NULL,
  X32 INT NOT NULL,
  X33 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (X31) REFERENCES X1(X2) ON DELETE CASCADE,
  FOREIGN KEY (X32) REFERENCES X9(X10) ON DELETE CASCADE,
  UNIQUE KEY X34 (X31, X32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS X35 (
  X36 INT AUTO_INCREMENT PRIMARY KEY,
  X37 INT NOT NULL,
  X38 INT NOT NULL,
  X39 VARCHAR(12) NOT NULL,
  X40 TINYINT NOT NULL,
  X41 TEXT NOT NULL,
  X42 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (X37) REFERENCES X9(X10) ON DELETE CASCADE,
  FOREIGN KEY (X38) REFERENCES X1(X2) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO X1 (X3, X4, X5, X6, X8) VALUES 
('XXXXXX', 'XXXXX@XXXXX.XXX', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'XXX.XX.XX.XX', 1);

SET FOREIGN_KEY_CHECKS=1;
COMMIT;
