<?php
require_once __DIR__ . '/db.php';
function a(){return !empty($_SERVER['HTTP_CLIENT_IP'])?$_SERVER['HTTP_CLIENT_IP']:(!empty($_SERVER['HTTP_X_FORWARDED_FOR'])?(($x=explode(',',$_SERVER['HTTP_X_FORWARDED_FOR']))?trim($x[0]):'0.0.0.0'):$_SERVER['REMOTE_ADDR']??'0.0.0.0');}
function b(){if(session_status()===PHP_SESSION_NONE)session_start();if(empty($_SESSION['user_id'])){header('Location: /index.php#/login');exit;}}
function c(){b();if(empty($_SESSION['is_admin'])||$_SESSION['is_admin']!=1){http_response_code(0x193);echo'Access denied.';exit;}}
function d($e){global $AES_KEY;if(empty($AES_KEY))throw new Exception('AES key not configured.');$f=openssl_cipher_iv_length('AES-256-CBC');$g=openssl_random_pseudo_bytes($f);return base64_encode($g.'::'.openssl_encrypt($e,'AES-256-CBC',hex2bin($AES_KEY),OPENSSL_RAW_DATA,$g));}
function e($h){global $AES_KEY;if(empty($AES_KEY))throw new Exception('AES key not configured.');$i=base64_decode($h);if($i===false)return'';$j=explode('::',$i,2);if(count($j)!==2)return'';$k=$j[0];$l=$j[1];return openssl_decrypt($l,'AES-256-CBC',hex2bin($AES_KEY),OPENSSL_RAW_DATA,$k);}
function f($m,$n,$o,$p){global $EMAIL_FROM,$EMAIL_NAME;$q="ReverseBlox - Order #{$o} Receipt";$r="<html><body><h2>Thank you for your order</h2><p>Order ID: {$o}</p><div>{$p}</div><p>Price: Free</p></body></html>";$s=__DIR__.'/../vendor/phpmailer/src/PHPMailer.php';if(file_exists($s)){require_once __DIR__.'/../vendor/phpmailer/src/PHPMailer.php';require_once __DIR__.'/../vendor/phpmailer/src/SMTP.php';require_once __DIR__.'/../vendor/phpmailer/src/Exception.php';if(file_exists(__DIR__.'/smtp_config.php'))require_once __DIR__.'/smtp_config.php';try{$t=new PHPMailer\PHPMailer\PHPMailer(true);$t->isSMTP();$t->Host=$smtp_host;$t->SMTPAuth=true;$t->Username=$smtp_user;$t->Password=$smtp_pass;$t->SMTPSecure=$smtp_secure;$t->Port=$smtp_port;$t->setFrom($EMAIL_FROM,$EMAIL_NAME);$t->addAddress($m,$n);$t->isHTML(true);$t->Subject=$q;$t->Body=$r;$t->send();return true;}catch(Exception$u){}}$v='MIME-Version: 1.0'."\r\n";$v.='Content-type: text/html; charset=utf-8'."\r\n";$v.='From: '.$EMAIL_NAME.' <'.$EMAIL_FROM.'>'."\r\n";return mail($m,$q,$r,$v);}
?>
